markdown: rdiscount
permalink: /:title/
url: http://aguardar.github.io/
name: aguardar blog
author: aguardar
email: zk_michael@qq.com
duoshuo: aguardar
weibo: 2779129061
github: aguardar
pygments: true
safe: true
paginate: 20
about: "这里是 aguardar 的个人博客"
